[package]
name = "draft_render"
version = "0.1.0"
edition = "2024"

[dependencies]
draft_window = { path = "../draft_window" }
draft_graphics = { path = "../draft_graphics" }
draft_mesh = { path = "../draft_mesh" }
draft_shader = { path = "../draft_shader" }
draft_utils = { path = "../draft_utils" }

fyrox-resource = { workspace = true }
nalgebra = { version = "0.34", features = ["bytemuck", "convert-glam030", "encase"] }

encase = "0.12"
wgpu = { version = "29.0.3", default-features = false, features = [
    "wgsl",
    "dx12",
    "metal",
    "vulkan",
    "naga-ir",
    "fragile-send-sync-non-atomic-wasm",
] }
thiserror = { version = "2.0" }
bytemuck = { version = "1.23.2", features = ["derive"] }
nonmax = "0.5"
